import Link from "next/link";
import { requireCustomer } from "@/server/auth";
import { cartTotal } from "@/server/cart";
import { db } from "@/server/db";
import { customerName } from "@/components/customer-presentation";
import { CartItemControls } from "@/components/cart-item-controls";
import { ProductVisual } from "@/components/product-visual";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
export default async function Cart(){const user=await requireCustomer(),cart=await db.cart.findFirst({where:{userId:user.id,status:"ACTIVE"},include:{items:{include:{product:{include:{images:{orderBy:{sortOrder:"asc"}},variants:true}}}}}}),items=cart?.items??[],total=cartTotal(items);return <main><SiteHeader/><section className="bag-page shell"><div className="page-heading"><div><p className="eyebrow">Your bag</p><h1>Collected pieces.</h1></div>{items.length>0&&<Link className="text-link" href="/shop">Continue shopping</Link>}</div>{items.length?<div className="bag-layout"><section className="bag-lines">{items.map(item=>{const variant=item.variantId?item.product.variants.find(value=>value.id===item.variantId):null,price=variant?.price??item.product.salePrice??item.product.price,available=(variant?.stockQuantity??item.product.stockQuantity)>=item.quantity;return <article className="bag-line" key={item.id}><ProductVisual images={item.product.images} alt={customerName(item.product.name,"Heritage object")} sizes="(max-width: 700px) 34vw, 160px" className="bag-line__image"/><div className="bag-line__details"><p className="eyebrow">{item.product.material??"VISAMGI collection"}</p><h2>{customerName(item.product.name,"Heritage object")}</h2>{variant&&<p>{variant.name}</p>}<small className={available?"":"form-error"}>{available?"Available to order":"Availability changed — update your bag before checkout."}</small><CartItemControls itemId={item.id} quantity={item.quantity}/></div><div className="bag-line__price"><span>₹{price.toString()} each</span><strong>₹{price.mul(item.quantity).toString()}</strong></div></article>})}</section><aside className="bag-summary"><p className="eyebrow">Order summary</p><p><span>Subtotal</span><strong>₹{total.toString()}</strong></p><small>Shipping is confirmed after selecting a delivery address.</small><Link className="button" href="/checkout">Continue to checkout</Link></aside></div>:<div className="empty-state empty-state--compact"><p className="eyebrow">Your bag</p><h2>Your bag is waiting for its first object.</h2><p>Explore the collection and save something that speaks to your home.</p><Link className="button" href="/shop">Explore the collection</Link></div>}</section><SiteFooter/></main>;}
