import { Prisma, StockStatus } from "@prisma/client";
import { z } from "zod";
import { db } from "@/server/db";

const slug = z.string().trim().min(2).max(120).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/);
export const categoryInput = z.object({ name:z.string().trim().min(2).max(120), slug, description:z.string().max(2000).optional().nullable(), imageUrl:z.string().startsWith("/images/").optional().nullable(), published:z.boolean(), sortOrder:z.coerce.number().int().min(0).default(0) });
export const productInput = z.object({ name:z.string().trim().min(2).max(180), slug, description:z.string().trim().min(10).max(12000), shortDescription:z.string().max(300).optional().nullable(), sku:z.string().trim().min(2).max(80), price:z.coerce.number().positive(), salePrice:z.coerce.number().positive().optional().nullable(), categoryId:z.string().trim().min(1).max(191), published:z.boolean(), featured:z.boolean(), stockQuantity:z.coerce.number().int().min(0), lowStockThreshold:z.coerce.number().int().min(0), material:z.string().max(80).optional().nullable(), color:z.string().max(80).optional().nullable() }).refine(v => !v.salePrice || v.salePrice <= v.price, { message:"Sale price cannot exceed price", path:["salePrice"] });
const status = (stock:number, threshold:number):StockStatus => stock === 0 ? "OUT_OF_STOCK" : stock <= threshold ? "LOW_STOCK" : "IN_STOCK";
export async function recordAudit(actorId:string, action:string, entityType:string, entityId:string, metadata?:Prisma.InputJsonValue) { await db.auditLog.create({data:{actorId,action,entityType,entityId,metadata}}); }
export async function adjustStock(actorId:string, productId:string, delta:number, note?:string) { if (!Number.isInteger(delta) || delta === 0) throw new Error("Enter a non-zero whole-number adjustment."); return db.$transaction(async tx => { const product=await tx.product.findUnique({where:{id:productId}}); if(!product) throw new Error("Product not found."); const next=product.stockQuantity+delta; if(next<0) throw new Error("Adjustment would make stock negative."); await tx.product.update({where:{id:productId},data:{stockQuantity:next,stockStatus:status(next,product.lowStockThreshold)}}); const transaction=await tx.inventoryTransaction.create({data:{productId,delta,reason:"ADJUSTMENT",note,actorId}}); await tx.auditLog.create({data:{actorId,action:"INVENTORY_ADJUSTED",entityType:"Product",entityId:productId,metadata:{previous:product.stockQuantity,next,delta}}}); return transaction; }); }
