"use server";
import { revalidatePath } from "next/cache";
import { requireAdmin } from "@/server/auth";
import { db } from "@/server/db";
import { productInput, recordAudit } from "@/server/admin";
export async function createProduct(form:FormData){const admin=await requireAdmin();const v=productInput.parse({name:form.get("name"),slug:form.get("slug"),description:form.get("description"),shortDescription:form.get("shortDescription")||null,sku:form.get("sku"),price:form.get("price"),salePrice:form.get("salePrice")||null,categoryId:form.get("categoryId"),published:form.get("published")==="on",featured:form.get("featured")==="on",stockQuantity:form.get("stockQuantity")||0,lowStockThreshold:form.get("lowStockThreshold")||2,material:form.get("material")||null,color:form.get("color")||null});const state=v.stockQuantity===0?"OUT_OF_STOCK":v.stockQuantity<=v.lowStockThreshold?"LOW_STOCK":"IN_STOCK";const product=await db.$transaction(async tx=>{const p=await tx.product.create({data:{...v,stockStatus:state}});if(v.stockQuantity) await tx.inventoryTransaction.create({data:{productId:p.id,delta:v.stockQuantity,reason:"INITIAL",actorId:admin.id}});await tx.auditLog.create({data:{actorId:admin.id,action:"PRODUCT_CREATED",entityType:"Product",entityId:p.id}});return p});revalidatePath("/admin/products");}
export async function archiveProduct(form:FormData){const admin=await requireAdmin();const id=String(form.get("id"));await db.product.update({where:{id},data:{archivedAt:new Date(),published:false}});await recordAudit(admin.id,"PRODUCT_ARCHIVED","Product",id);revalidatePath("/admin/products");}
export async function updateProduct(id:string,form:FormData){const admin=await requireAdmin();const existing=await db.product.findUnique({where:{id}});if(!existing)throw new Error("Product not found.");const v=productInput.parse({name:form.get("name"),slug:form.get("slug"),description:form.get("description"),shortDescription:form.get("shortDescription")||null,sku:form.get("sku"),price:form.get("price"),salePrice:form.get("salePrice")||null,categoryId:form.get("categoryId"),published:form.get("published")==="on",featured:form.get("featured")==="on",stockQuantity:existing.stockQuantity,lowStockThreshold:form.get("lowStockThreshold"),material:form.get("material")||null,color:form.get("color")||null});const stockStatus=existing.stockQuantity===0?"OUT_OF_STOCK":existing.stockQuantity<=v.lowStockThreshold?"LOW_STOCK":"IN_STOCK";await db.product.update({where:{id},data:{...v,stockStatus}});await recordAudit(admin.id,"PRODUCT_UPDATED","Product",id);revalidatePath(`/admin/products/${id}`);revalidatePath("/admin/products");}
const imageUrl=(value:FormDataEntryValue|null)=>{const url=String(value||"");if(!url.startsWith("/images/"))throw new Error("Use an approved local /images/ reference.");return url;};
export async function addImage(id:string,form:FormData){const admin=await requireAdmin(),url=imageUrl(form.get("url"));await db.$transaction(async tx=>{const count=await tx.productImage.count({where:{productId:id}});await tx.productImage.create({data:{productId:id,url,alt:String(form.get("alt")||"VISAMGI product image"),sortOrder:count,isPrimary:count===0}});await tx.auditLog.create({data:{actorId:admin.id,action:"PRODUCT_IMAGE_ADDED",entityType:"Product",entityId:id}})});revalidatePath(`/admin/products/${id}`);}
export async function reorderImages(id:string,form:FormData){const admin=await requireAdmin();const ids=String(form.get("ids")||"").split(",").filter(Boolean),owned=await db.productImage.count({where:{productId:id,id:{in:ids}}});if(owned!==ids.length)throw new Error("Invalid image selection.");await db.$transaction(async tx=>{for(const [sortOrder,imageId] of ids.entries())await tx.productImage.update({where:{id:imageId},data:{sortOrder,isPrimary:sortOrder===0}});await tx.auditLog.create({data:{actorId:admin.id,action:"PRODUCT_IMAGES_REORDERED",entityType:"Product",entityId:id}})});revalidatePath(`/admin/products/${id}`);}
export async function removeImage(id:string,imageId:string){const admin=await requireAdmin();const image=await db.productImage.findFirst({where:{id:imageId,productId:id}});if(!image)throw new Error("Image not found.");await db.$transaction(async tx=>{await tx.productImage.delete({where:{id:imageId}});const rest=await tx.productImage.findMany({where:{productId:id},orderBy:{sortOrder:"asc"}});for(const [sortOrder,item] of rest.entries())await tx.productImage.update({where:{id:item.id},data:{sortOrder,isPrimary:sortOrder===0}});await tx.auditLog.create({data:{actorId:admin.id,action:"PRODUCT_IMAGE_REMOVED",entityType:"Product",entityId:id}})});revalidatePath(`/admin/products/${id}`);}
export async function saveVariant(id:string,form:FormData){const admin=await requireAdmin(),variantId=String(form.get("variantId")||"");const price=form.get("price")?Number(form.get("price")):null,stock=Number(form.get("stockQuantity")),sku=String(form.get("sku")),name=String(form.get("name"));if(!name||!sku||!Number.isInteger(stock)||stock<0||price!==null&&(!Number.isFinite(price)||price<=0))throw new Error("Variant fields are invalid.");let attributes:object;try{attributes=JSON.parse(String(form.get("attributes")||"{}"));}catch{throw new Error("Attributes must be valid JSON.");}const data={productId:id,name,sku,attributes,price,stockQuantity:stock};if(variantId){const existing=await db.productVariant.findFirst({where:{id:variantId,productId:id}});if(!existing)throw new Error("Variant not found.");await db.productVariant.update({where:{id:variantId},data});}else await db.productVariant.create({data});await recordAudit(admin.id,variantId?"VARIANT_UPDATED":"VARIANT_CREATED","Product",id);revalidatePath(`/admin/products/${id}`);}
export async function removeVariant(id:string,variantId:string){const admin=await requireAdmin();const variant=await db.productVariant.findFirst({where:{id:variantId,productId:id}});if(!variant)throw new Error("Variant not found.");await db.productVariant.delete({where:{id:variantId}});await recordAudit(admin.id,"VARIANT_DELETED","Product",id);revalidatePath(`/admin/products/${id}`);}
