"use server";
import { mkdir, unlink, writeFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import path from "node:path";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdmin } from "@/server/auth";
import { db } from "@/server/db";
import { productInput, recordAudit } from "@/server/admin";

type ExistingProduct={slug:string;sku:string;stockQuantity:number};
export type ImageUploadState={error:string;success:string};
const imageTypes:Record<string,string>={"image/jpeg":"jpg","image/png":"png","image/webp":"webp"};
const normalizedSlug=(value:FormDataEntryValue|null)=>String(value??"").trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");
function refreshProductViews(id?:string){revalidatePath("/");revalidatePath("/shop");revalidatePath("/shop/[slug]","page");revalidatePath("/shop/product/[slug]","page");revalidatePath("/admin/products");if(id)revalidatePath(`/admin/products/${id}`);}
function cleanedSalePrice(price:FormDataEntryValue|null,sale:FormDataEntryValue|null){const p=Number(price),s=Number(sale);return sale&&Number.isFinite(s)&&s>0&&s<=p?sale:null;}
function productValues(form:FormData,existing?:ExistingProduct){const name=form.get("name"),slug=existing?normalizedSlug(existing.slug):normalizedSlug(name),generatedSku=`VIS-${slug.toUpperCase().slice(0,32)}-${randomUUID().slice(0,8).toUpperCase()}`;return productInput.parse({name,slug,sku:existing?.sku??generatedSku,description:form.get("description"),shortDescription:form.get("shortDescription")||null,price:form.get("price"),salePrice:cleanedSalePrice(form.get("price"),form.get("salePrice")),categoryId:form.get("categoryId"),published:form.get("published")==="on",featured:form.get("featured")==="on",stockQuantity:existing?.stockQuantity??(form.get("stockQuantity")||0),lowStockThreshold:form.get("lowStockThreshold")||2,material:form.get("material")||null,color:form.get("color")||null});}
export async function createProduct(form:FormData){const admin=await requireAdmin(),value=productValues(form),stockStatus=value.stockQuantity===0?"OUT_OF_STOCK":value.stockQuantity<=value.lowStockThreshold?"LOW_STOCK":"IN_STOCK",product=await db.$transaction(async tx=>{const created=await tx.product.create({data:{...value,stockStatus}});if(value.stockQuantity)await tx.inventoryTransaction.create({data:{productId:created.id,delta:value.stockQuantity,reason:"INITIAL",actorId:admin.id}});await tx.auditLog.create({data:{actorId:admin.id,action:"PRODUCT_CREATED",entityType:"Product",entityId:created.id}});return created;});refreshProductViews(product.id);redirect(`/admin/products/${product.id}`);}
export async function archiveProduct(form:FormData){const admin=await requireAdmin(),id=String(form.get("id"));await db.product.update({where:{id},data:{archivedAt:new Date(),published:false}});await recordAudit(admin.id,"PRODUCT_ARCHIVED","Product",id);refreshProductViews(id);}
export async function updateProduct(id:string,form:FormData){const admin=await requireAdmin(),existing=await db.product.findUnique({where:{id}});if(!existing)throw new Error("Product not found.");const value=productValues(form,existing),stockStatus=existing.stockQuantity===0?"OUT_OF_STOCK":existing.stockQuantity<=value.lowStockThreshold?"LOW_STOCK":"IN_STOCK";await db.product.update({where:{id},data:{...value,stockStatus}});await recordAudit(admin.id,"PRODUCT_UPDATED","Product",id);refreshProductViews(id);}
export async function uploadProductImage(id:string,_:ImageUploadState,form:FormData):Promise<ImageUploadState>{const admin=await requireAdmin(),file=form.get("image"),alt=String(form.get("alt")||"VISAMGI product image").trim(),makePrimary=form.get("makePrimary")==="on";if(!(file instanceof File)||file.size===0)return{error:"Choose an image to upload.",success:""};const extension=imageTypes[file.type];if(!extension)return{error:"Use a JPG, PNG, or WebP image.",success:""};if(file.size>5*1024*1024)return{error:"Use an image smaller than 5 MB.",success:""};let storedPath="";try{const filename=`${randomUUID()}.${extension}`,directory=path.join(process.cwd(),"public","uploads","products");storedPath=path.join(directory,filename);await mkdir(directory,{recursive:true});await writeFile(storedPath,Buffer.from(await file.arrayBuffer()));const url=`/uploads/products/${filename}`;await db.$transaction(async tx=>{const count=await tx.productImage.count({where:{productId:id}}),isPrimary=count===0||makePrimary;if(isPrimary)await tx.productImage.updateMany({where:{productId:id},data:{isPrimary:false,sortOrder:{increment:1}}});await tx.productImage.create({data:{productId:id,url,alt:alt||"VISAMGI product image",sortOrder:isPrimary?0:count,isPrimary}});await tx.auditLog.create({data:{actorId:admin.id,action:"PRODUCT_IMAGE_UPLOADED",entityType:"Product",entityId:id}})});refreshProductViews(id);return{error:"",success:"Image saved and collection refreshed."};}catch(error){if(storedPath)await unlink(storedPath).catch(()=>undefined);return{error:error instanceof Error?error.message:"Image could not be uploaded.",success:""};}}
export async function reorderImages(id:string,form:FormData){const admin=await requireAdmin(),ids=String(form.get("ids")||"").split(",").filter(Boolean),owned=await db.productImage.count({where:{productId:id,id:{in:ids}}});if(owned!==ids.length)throw new Error("Invalid image selection.");await db.$transaction(async tx=>{for(const [sortOrder,imageId]of ids.entries())await tx.productImage.update({where:{id:imageId},data:{sortOrder,isPrimary:sortOrder===0}});await tx.auditLog.create({data:{actorId:admin.id,action:"PRODUCT_IMAGES_REORDERED",entityType:"Product",entityId:id}})});refreshProductViews(id);}
export async function removeImage(id:string,imageId:string){const admin=await requireAdmin(),image=await db.productImage.findFirst({where:{id:imageId,productId:id}});if(!image)throw new Error("Image not found.");await db.$transaction(async tx=>{await tx.productImage.delete({where:{id:imageId}});const rest=await tx.productImage.findMany({where:{productId:id},orderBy:{sortOrder:"asc"}});for(const [sortOrder,item]of rest.entries())await tx.productImage.update({where:{id:item.id},data:{sortOrder,isPrimary:sortOrder===0}});await tx.auditLog.create({data:{actorId:admin.id,action:"PRODUCT_IMAGE_REMOVED",entityType:"Product",entityId:id}})});refreshProductViews(id);}
export async function saveVariant(id:string,form:FormData){const admin=await requireAdmin(),variantId=String(form.get("variantId")||""),price=form.get("price")?Number(form.get("price")):null,stock=Number(form.get("stockQuantity")),sku=String(form.get("sku")),name=String(form.get("name"));if(!name||!sku||!Number.isInteger(stock)||stock<0||price!==null&&(!Number.isFinite(price)||price<=0))throw new Error("Variant fields are invalid.");let attributes:object;try{attributes=JSON.parse(String(form.get("attributes")||"{}"));}catch{throw new Error("Attributes must be valid JSON.");}const data={productId:id,name,sku,attributes,price,stockQuantity:stock};if(variantId){const existing=await db.productVariant.findFirst({where:{id:variantId,productId:id}});if(!existing)throw new Error("Variant not found.");await db.productVariant.update({where:{id:variantId},data});}else await db.productVariant.create({data});await recordAudit(admin.id,variantId?"VARIANT_UPDATED":"VARIANT_CREATED","Product",id);refreshProductViews(id);}
export async function removeVariant(id:string,variantId:string){const admin=await requireAdmin(),variant=await db.productVariant.findFirst({where:{id:variantId,productId:id}});if(!variant)throw new Error("Variant not found.");await db.productVariant.delete({where:{id:variantId}});await recordAudit(admin.id,"VARIANT_DELETED","Product",id);refreshProductViews(id);}
