-- Baseline generated from prisma/schema.prisma for a clean PostgreSQL database.
CREATE TYPE "UserRole" AS ENUM ('CUSTOMER','ADMIN');
CREATE TYPE "StockStatus" AS ENUM ('IN_STOCK','LOW_STOCK','OUT_OF_STOCK');
CREATE TYPE "InventoryReason" AS ENUM ('INITIAL','SALE','RETURN','ADJUSTMENT','CANCELLED','RESERVATION');
CREATE TYPE "CartStatus" AS ENUM ('ACTIVE','CONVERTED');
CREATE TYPE "PaymentMethod" AS ENUM ('RAZORPAY','COD');
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING','PAID','FAILED','REFUNDED');
CREATE TYPE "OrderStatus" AS ENUM ('PENDING','CONFIRMED','PROCESSING','SHIPPED','DELIVERED','CANCELLED','REFUNDED');
CREATE TYPE "DiscountType" AS ENUM ('PERCENTAGE','FIXED');

CREATE TABLE "User" ("id" TEXT NOT NULL,"email" TEXT NOT NULL,"passwordHash" TEXT NOT NULL,"name" TEXT,"phone" TEXT,"role" "UserRole" NOT NULL DEFAULT 'CUSTOMER',"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Session" ("id" TEXT NOT NULL,"tokenHash" TEXT NOT NULL,"userId" TEXT NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Session_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Address" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"fullName" TEXT NOT NULL,"phone" TEXT NOT NULL,"line1" TEXT NOT NULL,"line2" TEXT,"city" TEXT NOT NULL,"district" TEXT,"state" TEXT NOT NULL,"pincode" TEXT NOT NULL,"landmark" TEXT,"type" TEXT,"isDefault" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Address_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Category" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"slug" TEXT NOT NULL,"description" TEXT,"imageUrl" TEXT,"sortOrder" INTEGER NOT NULL DEFAULT 0,"published" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Category_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Product" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"slug" TEXT NOT NULL,"description" TEXT NOT NULL,"shortDescription" TEXT,"sku" TEXT NOT NULL,"price" DECIMAL(12,2) NOT NULL,"salePrice" DECIMAL(12,2),"stockQuantity" INTEGER NOT NULL DEFAULT 0,"lowStockThreshold" INTEGER NOT NULL DEFAULT 2,"stockStatus" "StockStatus" NOT NULL DEFAULT 'OUT_OF_STOCK',"categoryId" TEXT NOT NULL,"weight" DECIMAL(10,2),"dimensions" JSONB,"material" TEXT,"color" TEXT,"tags" TEXT[] DEFAULT ARRAY[]::TEXT[],"seoTitle" TEXT,"seoDescription" TEXT,"featured" BOOLEAN NOT NULL DEFAULT false,"published" BOOLEAN NOT NULL DEFAULT false,"archivedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Product_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ProductImage" ("id" TEXT NOT NULL,"productId" TEXT NOT NULL,"url" TEXT NOT NULL,"alt" TEXT NOT NULL,"sortOrder" INTEGER NOT NULL DEFAULT 0,"isPrimary" BOOLEAN NOT NULL DEFAULT false,CONSTRAINT "ProductImage_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ProductVariant" ("id" TEXT NOT NULL,"productId" TEXT NOT NULL,"sku" TEXT NOT NULL,"name" TEXT NOT NULL,"attributes" JSONB NOT NULL,"price" DECIMAL(12,2),"stockQuantity" INTEGER NOT NULL DEFAULT 0,CONSTRAINT "ProductVariant_pkey" PRIMARY KEY ("id"));
CREATE TABLE "InventoryTransaction" ("id" TEXT NOT NULL,"productId" TEXT NOT NULL,"delta" INTEGER NOT NULL,"reason" "InventoryReason" NOT NULL,"reference" TEXT,"note" TEXT,"actorId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "InventoryTransaction_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Cart" ("id" TEXT NOT NULL,"userId" TEXT,"sessionId" TEXT,"status" "CartStatus" NOT NULL DEFAULT 'ACTIVE',"convertedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Cart_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CartItem" ("id" TEXT NOT NULL,"cartId" TEXT NOT NULL,"productId" TEXT NOT NULL,"variantId" TEXT,"quantity" INTEGER NOT NULL,CONSTRAINT "CartItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Order" ("id" TEXT NOT NULL,"orderNumber" TEXT NOT NULL,"userId" TEXT,"addressSnapshot" JSONB NOT NULL,"subtotal" DECIMAL(12,2) NOT NULL,"shipping" DECIMAL(12,2) NOT NULL,"tax" DECIMAL(12,2) NOT NULL DEFAULT 0,"discount" DECIMAL(12,2) NOT NULL DEFAULT 0,"total" DECIMAL(12,2) NOT NULL,"currency" VARCHAR(3) NOT NULL DEFAULT 'INR',"checkoutToken" TEXT,"paymentMethod" "PaymentMethod" NOT NULL,"paymentStatus" "PaymentStatus" NOT NULL DEFAULT 'PENDING',"orderStatus" "OrderStatus" NOT NULL DEFAULT 'PENDING',"couponCode" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Order_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OrderItem" ("id" TEXT NOT NULL,"orderId" TEXT NOT NULL,"productId" TEXT,"productNameSnapshot" TEXT NOT NULL,"skuSnapshot" TEXT NOT NULL,"variantNameSnapshot" TEXT,"variantAttributesSnapshot" JSONB,"priceSnapshot" DECIMAL(12,2) NOT NULL,"quantity" INTEGER NOT NULL,"subtotal" DECIMAL(12,2) NOT NULL,CONSTRAINT "OrderItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "InventoryReservation" ("id" TEXT NOT NULL,"orderId" TEXT NOT NULL,"productId" TEXT NOT NULL,"variantId" TEXT,"quantity" INTEGER NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "InventoryReservation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Payment" ("id" TEXT NOT NULL,"orderId" TEXT NOT NULL,"provider" TEXT NOT NULL,"providerOrderId" TEXT,"providerPaymentId" TEXT,"status" "PaymentStatus" NOT NULL DEFAULT 'PENDING',"amount" DECIMAL(12,2) NOT NULL,"rawResponse" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Payment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Coupon" ("id" TEXT NOT NULL,"code" TEXT NOT NULL,"type" "DiscountType" NOT NULL,"value" DECIMAL(12,2) NOT NULL,"minimumOrderValue" DECIMAL(12,2),"startDate" TIMESTAMP(3),"expiryDate" TIMESTAMP(3),"usageLimit" INTEGER,"usageCount" INTEGER NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Coupon_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ShippingConfiguration" ("id" TEXT NOT NULL,"supportedStates" TEXT[] DEFAULT ARRAY['Tamil Nadu']::TEXT[],"shippingCharge" DECIMAL(12,2),"freeShippingThreshold" DECIMAL(12,2),"deliveryEstimate" TEXT,"codEnabled" BOOLEAN NOT NULL DEFAULT true,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ShippingConfiguration_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SiteSetting" ("key" TEXT NOT NULL,"value" JSONB NOT NULL,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "SiteSetting_pkey" PRIMARY KEY ("key"));
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL,"actorId" TEXT,"action" TEXT NOT NULL,"entityType" TEXT NOT NULL,"entityId" TEXT,"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "User_email_key" ON "User"("email"); CREATE UNIQUE INDEX "Session_tokenHash_key" ON "Session"("tokenHash"); CREATE INDEX "Session_userId_expiresAt_idx" ON "Session"("userId","expiresAt"); CREATE UNIQUE INDEX "Category_name_key" ON "Category"("name"); CREATE UNIQUE INDEX "Category_slug_key" ON "Category"("slug"); CREATE UNIQUE INDEX "Product_slug_key" ON "Product"("slug"); CREATE UNIQUE INDEX "Product_sku_key" ON "Product"("sku"); CREATE INDEX "Product_categoryId_published_idx" ON "Product"("categoryId","published"); CREATE INDEX "Product_material_idx" ON "Product"("material"); CREATE INDEX "Product_stockStatus_idx" ON "Product"("stockStatus"); CREATE INDEX "Product_archivedAt_idx" ON "Product"("archivedAt"); CREATE INDEX "ProductImage_productId_sortOrder_idx" ON "ProductImage"("productId","sortOrder"); CREATE UNIQUE INDEX "ProductVariant_sku_key" ON "ProductVariant"("sku"); CREATE INDEX "InventoryTransaction_productId_createdAt_idx" ON "InventoryTransaction"("productId","createdAt"); CREATE UNIQUE INDEX "Cart_sessionId_key" ON "Cart"("sessionId"); CREATE INDEX "Cart_userId_status_idx" ON "Cart"("userId","status"); CREATE UNIQUE INDEX "CartItem_cartId_productId_variantId_key" ON "CartItem"("cartId","productId","variantId"); CREATE UNIQUE INDEX "Order_orderNumber_key" ON "Order"("orderNumber"); CREATE UNIQUE INDEX "Order_checkoutToken_key" ON "Order"("checkoutToken"); CREATE INDEX "Order_userId_createdAt_idx" ON "Order"("userId","createdAt"); CREATE INDEX "Order_orderStatus_createdAt_idx" ON "Order"("orderStatus","createdAt"); CREATE INDEX "InventoryReservation_orderId_idx" ON "InventoryReservation"("orderId"); CREATE INDEX "InventoryReservation_productId_variantId_idx" ON "InventoryReservation"("productId","variantId"); CREATE UNIQUE INDEX "Payment_orderId_key" ON "Payment"("orderId"); CREATE UNIQUE INDEX "Payment_providerOrderId_key" ON "Payment"("providerOrderId"); CREATE UNIQUE INDEX "Payment_providerPaymentId_key" ON "Payment"("providerPaymentId"); CREATE UNIQUE INDEX "Coupon_code_key" ON "Coupon"("code"); CREATE INDEX "AuditLog_entityType_entityId_idx" ON "AuditLog"("entityType","entityId");

ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Address" ADD CONSTRAINT "Address_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Product" ADD CONSTRAINT "Product_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "ProductImage" ADD CONSTRAINT "ProductImage_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ProductVariant" ADD CONSTRAINT "ProductVariant_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "InventoryTransaction" ADD CONSTRAINT "InventoryTransaction_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Cart" ADD CONSTRAINT "Cart_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "CartItem" ADD CONSTRAINT "CartItem_cartId_fkey" FOREIGN KEY ("cartId") REFERENCES "Cart"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "CartItem" ADD CONSTRAINT "CartItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Order" ADD CONSTRAINT "Order_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "InventoryReservation" ADD CONSTRAINT "InventoryReservation_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Payment" ADD CONSTRAINT "Payment_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
